-- AlterTable
ALTER TABLE "AnprLogs" ALTER COLUMN "meta_data" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Camera" ALTER COLUMN "installed" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "lastOnline" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "DetectionLog" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "timestamp" SET DATA TYPE TIMESTAMP(3);
